service: test-service

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  localPath: "../lib/index.js"
  modules:
    - ""
functions:
  hello:
    handler: handler.hello
    events:
      - schedule:
          rate: cron(0 10 * * ? *)
          name: test-crontab
          timezone: America/New_York
      - schedule:
          rate: cron(0 5 * * ? *)
          timezone: America/New_York
      - schedule:
          rate:
            - cron(0 5 * * ? *)
            - cron(0 6 * * ? *)
          timezone: America/New_York
validate: true
